### ISSUE TITLE
Blockscout Error when trying to Verify and Publish ERC20 [Internal Server Error]

### ISSUE THREAD

**Issue by YounesBM** [ConsenSys/quorum-kubernetes#110]
Hello @joshuafernandes,

I have successfully deployed Besu in a prod environment on Azure Kubernetes, my last problem was with a version of besu that hyperledger has fixed in the meantime.

I'm now trying to use Blockscout to get access to a block explorer. However, when I try to check/publish the code of an ERC20, I get the error "Internal Server Error".

To reproduce the bug, you have to click on the smart contract address, go to the "Code" tab and hit the "Verify and Publish" button.

When I use the hardhat framework, I also get an error: "Unsupported network".

Here are the logs of my pod "blockscout-0" :

![Logs Pod Blockscout](https://github.com/YounesBM/logs-quorum/blob/main/Blockscout.JPG?raw=true)

Do you know where it comes from?

Cheers,

Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM

Good to hear re your network, but this issue is one for the blockscout team. If I had to guess it may be that an API method it is calling isn't exposed but their team would be able to pinpoint this. I'd suggest opening this as an issue on blockscout

Keep us posted of the fix please though, if its' a patch I can update our version of it, else if its doco related I can add that in.

Cheers
Josh
