### ISSUE TITLE
Is it possible to change the number of replicas in the Statefulset?

### ISSUE THREAD

**Issue by miseyu** [ConsenSys/quorum-kubernetes#150]
## Summary
- I would like to do scale out by changing the replicas in the statefulset of the node, is quorum not supposed to do it that way?

refs: https://github.com/ConsenSys/quorum-kubernetes/blob/master/helm/charts/goquorum-node/templates/node-statefulset.yaml#L23

**Comment by Ezzahhh** [comment]
The charts are not intended to scale out more quorum nodes through replicas in the statefulset. You would need to run these helm install commands to add new nodes to the existing network: https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm#for-goquorum

**Comment by joshuafernandes** [comment]
Hi @miseyu 

The proper way to do this is to have additional nodes ie more members with any blockchain client. The reason is because each nodekey is unique and is treated as such, if there are many nodes that share the same nodekey this will cause collisions, more so in the context of validators.  

Becuase every node has the same data, you do not need to scale out the replicaset ie the protocol is designed to be fault tolerant. If you're trying to connect an app to the nodes and you need HA, put a service in front of two members/nodes etc and that should suffice

Cheers

**Comment by miseyu** [comment]
@Ezzahhh @joshuafernandes 
Thank you!
Now that we understand the reason for the above, we will take the form of applying multiple helm charts.

If possible, I was hoping to have something like quorum-kubernetes-operator like postgres-operator confluent-operator.

**Comment by joshuafernandes** [comment]
Hi @miseyu no worries, that's on our backlog but not yet had the chance to start work on it. Will keep you posted when we create an operator
