### ISSUE TITLE
Node not mining blocks

### ISSUE THREAD

**Issue by spaceh3ad** [ConsenSys/quorum-kubernetes#177]
I ve set up quorum locally using k9s and kubectl with:

```
helm install genesis ./charts/goquorum-genesis --namespace quorum --create-namespace --values ./values/genesis-goquorum.yml

helm install validator-1 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml
helm install validator-2 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml
helm install validator-3 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml
helm install validator-4 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml

helm install rpc-1 ./charts/goquorum-node --namespace quorum --values ./values/reader.yml

helm install member-1 ./charts/goquorum-node --namespace quorum --values ./values/txnode.yml

```
![image](https://user-images.githubusercontent.com/52543683/215768129-b0a64024-350e-4abc-bee3-4aa7dd697cd3.png)

no block is being mined and I get error about genesis block mismatch:

![image (1)](https://user-images.githubusercontent.com/52543683/215762745-173b76f8-1563-45e2-9727-234e0d4c1c2f.png)
![image](https://user-images.githubusercontent.com/52543683/215762954-8365e05f-77dc-4398-ae2f-8fc70bd59f51.png)

curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1337}' http://localhost:8545
{"jsonrpc":"2.0","id":1337,"result":"0x0"}

I strictly followed the quorum docs on that. First time I lanuched the quorum it worked and I was able to deploy my smart contract, but then it suddenly stopped. I assume maybe it have cached some data strangely but on the other hand this shouldn't happen in kubernates.

**Comment by joshuafernandes** [comment]
Hello @spaceh3ad this is by design to help speed up a node restart or sync. eg: in the event that your node stops on production, it is not the nicest option to sync from scratch, rather you pick up the data from the appropriate storage volume. 

To get this to work on restarts etc, you have some options:
- fork the repo and alter the storage mechanism to use pod storage space rather than a PVC
- leave as is and delete the storageclass and PVCs; then restart your network on minikube
